### ISSUE TITLE
Revival todo list

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/k4ActsTracking#11]
This project has been sleeping for a bit but we are reviving it and I will use this issue to track some of the things to do:
- [ ] Split and update https://github.com/key4hep/k4ActsTracking/pull/10
  - [ ] Rename `GeoSvc` to `ActsGeoSvc`
  - [ ] Update to newer ACTS api (pass logger instead of loglevel)
  - [ ] Update CI tests
- [ ] Write "developer guide"
- [ ] Port further Gaudi algorithms from https://github.com/delitez/k4ActsTracking
  - [ ] and change them to use Gaudi functional once that is there
